name: JuicyRaspberryPie
version: ${project.version}
description: RaspberryJuice with a command Server
database: false
main: org.wensheng.juicyraspberrypie.JuicyRaspberryPie
api-version: 1.14
commands:
  p:
    description: execute python functions in pplugins
    usage: /<command> args
