#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#2-7-5-1.py
import turtle
turtle.home()
turtle.bk(300)
turtle.home()
turtle.fd(300)
turtle.home()
turtle.lt(90)
turtle.fd(300)
turtle.home()
turtle.rt(90)
turtle.fd(300)
turtle.home()
turtle.color('green')
turtle.circle(120)
turtle.home()
turtle.color('red')
turtle.circle(-60)
turtle.up()
turtle.color('blue')
turtle.goto(0,-120)
turtle.down()
turtle.circle(120)
print('按回车键退出')
input()